 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for ultrasonic driver
 *
 * Author: Nora Nagdi
 *
 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

extern uint8 g_edgeCount;

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASONIC_TRIGGER_PORT_ID        PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID         PIN5_ID

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/

/*
 * Description :
 * initialize the ultrasonic Driver.
 */
void Ultrasonic_init(void);


/*
 * Description :
 * send the trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);


/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time generated by the ultrasonic.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
